apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1  # Specify the number of replicas
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodbcontainer
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
        volumeMounts:
        - name: pvc
          mountPath: /data/db
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: mongodbpvc
